- hosts: jenkins
  sudo: true
  roles:
    - role: geerlingguy.certbot
      certbot_auto_renew_user: cloud-user
      certbot_auto_renew_minute: 20
      certbot_auto_renew_hour: 5
    - role: RealSalmon.jenkins-master
      jenkins_master_nginx_ssl: true
      jenkins_master_nginx_proxy: true
  post_tasks:
    - shell: service nginx stop
    - shell: certbot register --agree-tos --email jukka.nousiainen@csc.fi
      ignore_errors: true
    - shell: dig +short -x $(curl http://ip4.me 2>&1|egrep -o '((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')|sed 's/.$//'
      register: fqdn
    - shell: certbot certonly --noninteractive --standalone -d "{{ fqdn.stdout }}"
    - shell: cd /etc/nginx/ssl;mv _.crt _.crt.old;mv _.key _.key.old
      args:
        creates: /etc/nginx/ssl/_.crt.old
    - shell: "ln -s /etc/letsencrypt/live/{{ fqdn.stdout }}/privkey.pem /etc/nginx/ssl/_.crt"
      ignore_errors: true
    - shell: "ln -s /etc/letsencrypt/live/{{ fqdn.stdout }}/privkey.pem /etc/nginx/ssl/_.key"
      ignore_errors: true
    - shell: service nginx start
